apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ambassador-crds.yaml
- ambassador-rbac.yaml
- ambassador-service.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ambassador
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra/ambassador
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client