---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: ssss-backend
  namespace: flux-system
spec:
  image: ghcr.io/Davidsoff/ssss_backend
  interval: 1m0s
  secretRef:
    name: gh-registry
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: ssss-frontend
  namespace: flux-system
spec:
  image: ghcr.io/Davidsoff/ssss_frontend
  interval: 1m0s
  secretRef:
    name: gh-registry