apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- imagePolicy.yaml
- imageRepository.yaml
- imageUpdateAutomation.yaml
- notificationProvider.yaml
- notificationSecret.yaml
- alert.yaml
