apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ssss-gh-notifications
  namespace: flux-system
spec:
  encryptedData:
    notificationkey: AgAREnoSCIQWH33DLq/zTpRmZhbaqSuRs50MWWcOD7Yv+RYuCnDw6nefJTX0bYe2TSH4mEXgnmCsnXQtm6L8vyEEiRhXQJ9LCyhuHtwwg5t1BqRWWxL3Y1OPJO+FIfI5PTZckPobvZOdND6m57gUI5adOg/3shmnE36kLDmmQHibYQH9etu0ocHJAPgNbLJ/8OQI6wuBqAO4tOA2afoMTsC3SGQh4WZMk9smqyLK0sLZVQwriqbncO05EvWHvA41E1A2DjYSr2d0OwZC6gQhH5BYG/CLeiZUS4O2zrkyIX5os6qgo9sjIVDeTO25EJTA16Fad7Ykj6bIoq36NdXEer5zx7tKMUZPqdVzrIathH80SGS8TAV+KKRgK4x9drWwjNorJFcZar7OG3FNfSlvWDIO24FwGT8TLsFbCElL0N8TFFqKCuEAKQPceqLMe20XLJdBjtPSeRJO3CBkhU3zL2BS0sw7fCxqXJ9FKqPylCF9+IUfCH0xahzRtAJ5ECnCq7omtSjuAPftnfL6teDjLxLQyUlh7BbFLcfM8wkrovFRrAZ8/WpBfBjrkVvEk88YJIVWYlOXo3Zlkzt6ge8k1OOMRpytpkbnfVL1piflkz2h9Qsa/m+Mh33iq/ET8EnWThFLhmbALs3v4K3s7CASDHQHwFmJbt4rcdYR1TOObcMdTEO2nEy/djxPUhHagFnMFRPx
  template:
    metadata:
      creationTimestamp: null
      name: ssss-gh-notifications
      namespace: flux-system

