-- INSERT INTO HOUSEHOLD (id, address, country, name, postal_code)
-- VALUES (001, 'Leidseplein 1', 'Hollandia', 'Thuis', '1011AB');
--
-- INSERT INTO HOUSEHOLD (id, address, country, name, postal_code)
-- VALUES (002, 'Leidseplein 3', 'Turkije', 'Doner', '1011TU' );
--
-- INSERT INTO HOUSEHOLD (id, address, country, name, postal_code)
-- VALUES (003, 'Leidseplein 6', 'Marokko', 'Watser?', '1011MA' );
