kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: ssss
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - secretName: supply-apps-soffware-nl-tls
      hosts:
        - supply.apps.soffware.nl
  rules:
    - host: supply.apps.soffware.nl
      http:
        paths:
          - pathType: Prefix
            path: "/api"
            backend:
              serviceName: ssss
              servicePort: 8080