kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: ssss
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: ssss
              servicePort: 8080