name: Build and Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy frontend to github pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          angular_project_dir: frontend/supersimplesupplysystem
          build_configuration: production
          base_href: /my-project/
          deploy_branch: gh-pages